### ISSUE TITLE
CEL Holders and CEL Tokens

### ISSUE THREAD

**Issue by HeroHann** [bonham000/celsius-rewards-explorer#4]
Hello,
as already mentioned on twitter a graph with the top cel holders (and a representation of how much each one holds) and also a graph with the cel holdings of (top 500) users and the prozess of their holdings.

with such graphs everyone could see each week how the cel-tokens have been distributed due to selling and buying of whales…

also: a graph for the moving average of cel token per user…

also also: a graph for the loyality levels over time…

Thanks!

**Comment by bonham000** [comment]
Hi @HeroHann I have added something like this which is the top token holders for each token, take a look and let me know if that's what you are looking for.
